import java.util.Scanner;

public class Quset13 {

  public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);

    System.out.print("Enter the number of participants: ");
    int participants = scanner.nextInt();

    // Calculate the revenue.
    double revenue = participants * 2500;

    // Print the revenue.
    System.out.println("The revenue generated by the tour is $" + revenue + ".");
  }
}
